### ISSUE TITLE
Empty runtime config causes error with addon: runtime-config

### ISSUE THREAD

**Issue by tpoland** [genesis-community/bosh-genesis-kit#63]
When a runtime configuration has not yet been set for a newly deployed BOSH director the runtime-config operation will fail:

>`genesis do [director] -- runtime-config`
>Running runtime-config addon for [director]
>
>The `netop` user is a local administrator account configured with
a 4096-bit RSA SSH key for authentication.  It can be used to perform
out-of-band, remote management of BOSH VMs when BOSH is misbehaving.
>
>Enable the netop account?  [y|n] > y
>
>The `sysop' user is a local administrator account configured with
a randomized password, for console-based authentication.  This can be
handy in vSphere environments when network-based authentication breaks.
>
>Enable the sysop account?  [y|n] > y
>No runtime config
>Exit code 1
>rc.yml: Root of YAML document is not a hash/map: type assertion to map[interface]interface{} failed
>
>Using environment 'https://[REDACT]:25555' as user 'admin'
>
>Fetching diff result:
>  Director responded with non-successful status code '400' response '{"code":440001,"description":"Manifest should be a hash"}'
>
>Exit code 1

**Suggested Change:**
Catch condition and ask user if they would like to use a "sensible" default config; if so, apply based on default config; if not, clean exit.

**Comment by VasylTretiakov** [comment]
The issue is caused by the fact that _bosh cli_ returns a (not so easily noticeable) newline character when _runtime-config_ is empty. As this makes the temp **rc.yml** file non-empty (1 byte), the kit's addon script cannot insert a valid empty YAML `--- {}` into **rc.yml**. This eventually leads to _spruce_ complaining (and for a very good reason).
As stated [here](https://github.com/geofffranks/spruce/issues/256), _spruce_ does properly handle valid YAML files including those that have empty content.
I am submitting a PR to fix this.
